### ISSUE TITLE
No reachable servers

### ISSUE THREAD

**Issue by ragnarlodbrok1992** [ragnarlodbrok1992/go-json-api#5]
panic: no reachable servers

goroutine 1 [running]:
_/C_/Users/Maciek/GoglandProjects/go-json-api/src/database.CreateDefaultLivingPlanet()
	C:/Users/Maciek/GoglandProjects/go-json-api/src/database/init_db_structure.go:9 +0x2e3
main.main()
	C:/Users/Maciek/GoglandProjects/go-json-api/src/main/main.go:16 +0xec

The line in question is: database.CreateDefaultLivingPlanet() in "src/main/main.go"

**Comment by ragnarlodbrok1992** [comment]
Feed variables in credentials.go in src/helpers with data.
For now, the variables are getting from os environment.
